### ISSUE TITLE
Reduction Lens

### ISSUE THREAD

**Issue by cbolgiano** [gjcroft/microscope#4]
What is the reduction lens you are using?

Thank you for putting this together. I have just started microscopy and have a similar rig. My raspi hq camera is directly mounted via c mount onto the stock Trinocular attachment that came with the swift 380t. The focus is off between the camera and the eye pieces when using a 10x lens on the binoculars.

The quality is good but from what I see one your youtube channel the quality can improve. I am not sure what I am missing.

**Comment by gjcroft** [comment]
it is a standard amscope reduction lens https://amscope.co.uk/collections/adapters/products/0-3x-c-mount-lens-adapter-for-video-camera-microscopes

Regarding the focus issue you can align the camera trinocular. Where the camera fits on there should be one or two small allen key screws which you can adjust so that what you see in the eye piece is the same focus as what the camera sees.

To be honest i tend to view on screen so this is not really an issue. Download the software to get improvements on the raspberry pi camera increasing the contrast a little and the sharpness alot makes a big difference from the standard view settings on the camera.

**Comment by cbolgiano** [comment]
Thank you for the information and time to answer my question.
